In [2]:
import numpy as np
import pandas as pd
import time
import cv2

In [3]:
res=[]

In [4]:
# print(scr[mx-9:mx+1, my:my+9,0])
# res = [scr[mx-9:mx+1, my:my+9,0]*ker2 ]
# print(res)

In [11]:
def hor_rd(mean):
    lim1=3*lim
    mean1=mean
    for i in range(my,shape[1]-lmd,lmd-2):
        low = list(mean - lim1)
        high = list(mean + lim1)
        res = [np.mean(scr[mx-lmd:mx+1, i:i+lmd,j]) for j in range(3)]
        
#         print("hor",i)
        if(res>low and res<high):
            res = np.array(res)
            mean = cv2.addWeighted(res,0.6,mean,0.4,0)
            newscr[mx-lmd:mx+1, i:i+lmd] = 255
            ver_rd(i,mean)
        else:
            newscr[mx-lmd:mx+1, i:i+lmd] = 0
            ver_rd(i,mean1)
#             print(res,low,high)
            if(res>2*low):
                break
            
    for i in range(my+lmd,0, -(lmd-2)):
        low = list(mean1 - lim1)
        high = list(mean1 + lim1)
        res = [np.mean(scr[mx-lmd:mx+1, i-lmd:i,j]) for j in range(3)]
#         print("hor",i)
        if(res>low and res<high):      
            res = np.array(res)
            mean1 = cv2.addWeighted(res,0.6,mean1,0.4,0)
            newscr[mx-lmd:mx+1, i-lmd:i] = 255
            ver_rd(i,mean1)
        else:
            newscr[mx-lmd:mx+1, i-lmd:i] = 0
            ver_rd(i,mean1)
#             print(res,low,high)
            if(res>2*low):
                break
            

In [12]:
def ver_rd(x,mean):
    lm = lim
    for i in range(mx,lmd+1,-(lmd-2)):
        lm += lm*0.01 
        low = mean - lm
        high = mean + lm
        mm = cv2.inRange(scr[i-lmd:i, x:x+lmd],low,high)
        newscr[i-lmd:i, x:x+lmd] = mm
#         if(np.mean(mm)>=255):
#             print("ver",np.mean(mm))
        res = [np.mean(scr[i-lmd:i, x:x+lmd,j]) for j in range(3)]
        res = np.array(res)
        mean = cv2.addWeighted(res,0.5,mean,0.5,0)
#             newscr[i-lmd:i, x:x+lmd] = 255
#         else:
#             newscr[i-lmd:i, x:x+lmd] = 0   

In [23]:
import numpy as np
import pandas as pd
import time
import cv2
y=200
lim = 3
lmd = 5

kernel = np.ones((3,3),np.uint8)
scr = cv2.imread('12.png')
scr = cv2.resize(scr, (680,480)) 
shape = scr.shape
newscr = np.zeros((shape[0],shape[1]),np.uint8)
mx = shape[0]
my = shape[1]//2
# print(shape,mx,my)
scr = cv2.bilateralFilter(scr,70,30,100)
# scr = cv2.cvtColor(blur, cv2.COLOR_BGR2HSV)
mean = [np.mean(scr[440:480,200:480, i]) for i in range(3)]
mean = np.array(mean)
hor_rd(mean)

newscr = cv2.morphologyEx(newscr,cv2.MORPH_OPEN,kernel, iterations = 1)
newscr = cv2.morphologyEx(newscr,cv2.MORPH_CLOSE,kernel, iterations = 1)
# newscr = cv2.morphologyEx(newscr,cv2.MORPH_OPEN,kernel, iterations = 1)
# newscr = cv2.erode(newscr,kernel,iterations=1)
cv2.destroyAllWindows()
# cv2.imshow('scr',scr)
# cv2.imshow('newscr',newscr)
band =  cv2.bitwise_and(scr,scr,mask = newscr)

cv2.imshow('blur',band)


sure_bg = cv2.dilate(newscr,kernel,iterations=1)
        # Finding sure foreground area
dist_transform = cv2.distanceTransform(newscr,cv2.DIST_L2,5)
ret, sure_fg = cv2.threshold(dist_transform,0.00000001*dist_transform.max(),255,0)
        # Finding unknown region
sure_fg = np.uint8(sure_fg)
unknown = cv2.subtract(sure_bg,sure_fg)
        # Marker labelling
ret, markers = cv2.connectedComponents(sure_fg)
print(markers)
        # Add one to all labels so that sure background is not 0, but 1
markers = markers+1
        # Now, mark the region of unknown with zero
markers[unknown==255] = 0


markers = cv2.watershed(scr,markers)
scr[markers == -1] = [0,0,255]
# print(markers)

cv2.imshow('sure_fg',sure_fg)
cv2.imshow('scr1',scr)
# cv2.imshow('sure_bg',sure_bg)



q=cv2.waitKey(1)
if q == 27:
    cv2.destroyAllWindows()

/Users/shreyashkawalkar/anaconda3/lib/python3.6/site-packages/numpy/core/fromnumeric.py:2889: RuntimeWarning: Mean of empty slice.
  out=out, **kwargs)
/Users/shreyashkawalkar/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py:80: RuntimeWarning: invalid value encountered in double_scalars
  ret = ret.dtype.type(ret / rcount)


[[  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0   0]
 ..., 
 [162 162 162 ..., 101   0   0]
 [162 162 162 ..., 101   0   0]
 [162 162 162 ..., 101   0   0]]


In [8]:
def crtr():
    def nothing(x):
        pass
    cv2.namedWindow(img)

    # create trackbars for color change
    cv2.createTrackbar('H',img,0,255,nothing)
    cv2.createTrackbar('S',img,0,255,nothing)
    cv2.createTrackbar('V',img,0,255,nothing)
    cv2.createTrackbar('H1',img,0,255,nothing)
    cv2.createTrackbar('S1',img,0,255,nothing)
    cv2.createTrackbar('V1',img,0,255,nothing)

In [9]:
import numpy as np
import pandas as pd
import time
import cv2
box = 5
st = 4
kernel = np.ones((3,3),np.uint8)
scr = cv2.imread('13.png')
scr = cv2.resize(scr, (680,480)) 
blur = cv2.bilateralFilter(scr,70,30,100)
hsv = cv2.cvtColor(blur, cv2.COLOR_BGR2HSV)
img = 'track'
crtr()
y,z = [np.mean(hsv[440:480,200:480, i]) for i in range(1,3)]


while True:
    a = cv2.getTrackbarPos('H',img)
    b = cv2.getTrackbarPos('S',img)
    c = cv2.getTrackbarPos('V',img)
    a1 = cv2.getTrackbarPos('H1',img)
    b1 = cv2.getTrackbarPos('S1',img)
    c1 = cv2.getTrackbarPos('V1',img)
#     a=27
#     b=20
#     c=20
#     x,y,z = [np.mean(hsv[440:480,200:480, i]) for i in range(3)]
    low = (np.uint8([0,y,z]) - [0,b,c])
    high = low + [180,2*b,2*c]
    print(low,high)
    mask = cv2.inRange(hsv,low,high)#np.uint8([a,b,c]),np.uint8([a1,b1,c1]))
    blur[440:480,200:480]=0
#     scr[mx-10:mx+1,my-8:my+3]=0
    # cv2.imshow('canny',canny)
#     cv2.imshow('src',scr)
    cv2.imshow('blur',blur)
    cv2.imshow('hsv',hsv)
    cv2.imshow('thresh',mask)


    q=cv2.waitKey(1)
    if q == 27:
    # time.sleep(30)
        cv2.destroyAllWindows()

[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]


KeyboardInterrupt: 

In [ ]:
q=0
road_mn = 100
kernel = np.ones((3,3),np.uint8)
while True:
    vrec = cv2.VideoCapture('v2.mp4',0)
    while True:
        w=0;
        ret, scr = vrec.read()
        if not ret:
            break
#         time.sleep()

        gray = cv2.cvtColor(scr, cv2.COLOR_BGR2GRAY)
        hls = cv2.cvtColor(scr, cv2.COLOR_BGR2HLS)
        hsv = cv2.cvtColor(scr, cv2.COLOR_BGR2HSV)
#         scr = cv2.bilateralFilter(scr,40,100,100)
        x,y,z = [np.mean(scr[335:355,160:460, i]) for i in range(3)]
        low = np.uint8([x,y,z]) - 20
        high = np.uint8([x,y,z]) + 20
        mask = cv2.inRange(scr,low,high)
        morp = cv2.morphologyEx(mask,cv2.MORPH_OPEN,kernel, iterations = 3)
#         can = cv2.Canny(morp, 0, 255)
        
#         h1, h2, h3 = [np.min(hsv[335:355,160:460, i]) for i in range(3)]
#         g1, g2, g3 = [np.max(hsv[335:355,160:460, i]) for i in range(3)]
#         low1 = np.uint8([h1, h2, h3])
#         high1 = np.uint8([g1, g2, g3])
#         mask2 = cv2.inRange(hls,low1,high1)
#         close = cv2.morphologyEx(mask,cv2.MORPH_CLOSE,kernel, iterations = 1)
#         close = cv2.erode(close,kernel,iterations=3)
        cv2.imshow('scr1',scr)
        cv2.imshow('scr11',mask) 
#         cv2.imshow('hls',hls)
        cv2.imshow('mask1',can)
        cv2.imshow('morp',morp)
#         cv2.imshow('mask2',mask2)
        
        
#         cv2.imshow('close',close)
        #75 365  405 365 75 265 405 265
        q = cv2.waitKey(1)
        if q == 27:
            cv2.destroyAllWindows()
            break
    if q == 27:
            cv2.destroyAllWindows()
            break
cv2.destroyAllWindows()

In [32]:
q=0
road_mn = 100
kernel = np.ones((5,5),np.uint8)
clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
while True:
    vrec = cv2.VideoCapture('v2.mp4',0)
    while True:
        ret, scr = vrec.read()
        if not ret:
            break
        time.sleep(.03)
        gray = cv2.cvtColor(scr, cv2.COLOR_BGR2GRAY)
        hls = cv2.cvtColor(scr, cv2.COLOR_BGR2HLS)
        hsv = cv2.cvtColor(scr, cv2.COLOR_BGR2HSV)
        scr = cv2.bilateralFilter(scr,40,75,75)
        
        x,y,z = [np.min(hls[335:355,160:460, i]) for i in range(3)]
        low = np.uint8([x,y,z]) * [1,0,1]
        high = low + [0,255,0]
        mask = cv2.inRange(hls, np.uint8([x,y,z]), np.uint8([x1,y1,z1]))

        cv2.imshow('scr1',scr)
        cv2.imshow('scr11',mask)
#         cv2.imshow('scr111',can)
#         cv2.imshow('scr1111',sure_fg)

        cv2.imshow('scr2',gray)
        cv2.imshow('hls',hls)
        cv2.imshow('hsv',hsv)
#         hsv[335:355,160:460]=higher_path
#         cv2.imshow('scr3',hsv)
#         cv2.imshow('scr4',res)
        
        #75 365  405 365 75 265 405 265
        q = cv2.waitKey(1)
        if q == 27:
            cv2.destroyAllWindows()
            break
    if q == 27:
            cv2.destroyAllWindows()
            break
cv2.destroyAllWindows()

In [38]:
        kernel = np.ones((5,5),np.uint8)
        ret, thresh = cv2.threshold(gray,0,255,cv2.THRESH_BINARY_INV)
        opening = cv2.morphologyEx(thresh,cv2.MORPH_OPEN,kernel, iterations = 2)
        # sure background area
        sure_bg = cv2.dilate(opening,kernel,iterations=3)
        # Finding sure foreground area
        dist_transform = cv2.distanceTransform(opening,cv2.DIST_L2,5)
        ret, sure_fg = cv2.threshold(dist_transform,0.7*dist_transform.max(),255,0)
        # Finding unknown region
        sure_fg = np.uint8(sure_fg)
        unknown = cv2.subtract(sure_bg,sure_fg)
        # Marker labelling
        ret, markers = cv2.connectedComponents(sure_fg)
        # Add one to all labels so that sure background is not 0, but 1
        markers = markers+1
        # Now, mark the region of unknown with zero
        markers[unknown==255] = 0
        markers = cv2.watershed(scr,markers)
        scr[markers == -1] = [255,0,0]
        cv2.imshow('scr1',scr)
#         scr = cv2.bilateralFilter(scr,9,75,75)
#         scr1 = cv2.morphologyEx(scr, cv2.MORPH_OPEN, kernel)
#         scr1 = cv2.morphologyEx(scr1, cv2.MORPH_CLOSE, kernel)
#         scr11 = cv2.morphologyEx(scr, cv2.MORPH_CLOSE, kernel)
#         scr11 = cv2.morphologyEx(scr11, cv2.MORPH_OPEN, kernel)
#         erosion = cv2.erode(scr,kernel,iterations = 1)
        
#         gray = cv2.cvtColor(scr, cv2.COLOR_BGR2GRAY)
#         hsv = cv2.cvtColor(scr, cv2.COLOR_BGR2HSV)
#         x,y,z =[ np.min(scr[335:355,160:460,i]) for i in range(3)]#,np.mean(scr[75:406, 265:366, 1],dtype='int'),np.mean(scr[75:406, 265:366, 2],dtype='int')
#         x1,y1,z1 =[ np.max(scr[335:355,160:460,i]) for i in range(3)]
#         lower_path = cv2.cvtColor(np.uint8([[[x,y,z]]]),cv2.COLOR_BGR2HSV)
#         higher_path = cv2.cvtColor(np.uint8([[[x1,y1,z1]]]),cv2.COLOR_BGR2HSV)
#         mask = cv2.inRange(hsv,lower_path,higher_path)
#         res = cv2.bitwise_and(scr,scr, mask= mask)

In [ ]:
import numpy as np
import pandas as pd
import time
import cv2
scr = cv2.imread('17.png')
scr = cv2.resize(scr, (680,480)) 
shape = scr.shape
mx = shape[0]
my = shape[1]//2
print(shape,mx,my)
scr[mx-10:mx+1,my-8:my+3]=0
gray = cv2.cvtColor(scr, cv2.COLOR_BGR2GRAY)
# cv2.imshow('canny',canny)
cv2.imshow('src',scr)
kernel = np.ones((5,5),np.uint8)
x,y,z = [np.mean(scr[440:480,200:480, i]) for i in range(3)]
low = np.uint8([x,y,z]) - 40
high = np.uint8([x,y,z]) + 40
thresh = cv2.inRange(scr,low,high)
opening = cv2.morphologyEx(thresh,cv2.MORPH_OPEN,kernel, iterations = 2)
        # sure background area
sure_bg = cv2.dilate(opening,kernel,iterations=3)
        # Finding sure foreground area
dist_transform = cv2.distanceTransform(opening,cv2.DIST_L2,5)
ret, sure_fg = cv2.threshold(dist_transform,0.0001*dist_transform.max(),255,0)
        # Finding unknown region
sure_fg = np.uint8(sure_fg)
unknown = cv2.subtract(sure_bg,sure_fg)
        # Marker labelling
ret, markers = cv2.connectedComponents(sure_fg)
print(markers)
        # Add one to all labels so that sure background is not 0, but 1
markers = markers+1
        # Now, mark the region of unknown with zero
markers[unknown==255] = 0
markers = cv2.watershed(scr,markers)
scr[markers == -1] = [0,0,255]
print(markers)
scr[440:480,200:480]=0
cv2.imshow('scr1',scr)
cv2.imshow('mask',thresh)
q=cv2.waitKey(1)
# if q == 27:
time.sleep(60)
cv2.destroyAllWindows()