In [7]:
import numpy as np
import pandas as pd
import time
import cv2

In [8]:
res=[]

In [9]:
# print(scr[mx-9:mx+1, my:my+9,0])
# res = [scr[mx-9:mx+1, my:my+9,0]*ker2 ]
# print(res)

In [10]:
def hor_rd(mean):
    lim1=3*lim
    mean1=mean
    for i in range(my,shape[1]-lmd,lmd-2):
#         low = mean - lim1
#         high = mean + lim1
#         res = np.mean(scr[mx-lmd:mx+1, i:i+lmd])
        
# #         print("hor",i)
#         if(res>low and res<high):
#             mean = np.array(mean)
#             mean = cv2.addWeighted(res,0.6,mean,0.4,0)
#             newscr[mx-lmd:mx+1, i:i+lmd] = 255
#             ver_rd(i,mean)
#         else:
#             newscr[mx-lmd:mx+1, i:i+lmd] = 0
        ver_rd(i,mean1)
#             print(res,low,high)
#             if(res>2*low):
#                 break
            
    for i in range(my+lmd,0, -(lmd-2)):
#         low = mean1 - lim1
#         high = mean1 + lim1
#         res = np.mean(scr[mx-lmd:mx+1, i-lmd:i])
# #         print("hor",i)
#         if(res>low and res<high):   
#             mean1 = np.array(mean1)
#             mean1 = cv2.addWeighted(res,0.6,mean1,0.4,0)
#             newscr[mx-lmd:mx+1, i-lmd:i] = 255
#             ver_rd(i,mean1)
#         else:
#             newscr[mx-lmd:mx+1, i-lmd:i] = 0
        ver_rd(i,mean1)
#             print(res,low,high)
#             if(res>2*low):
#                 break
            

In [11]:
def ver_rd(x,mean):
    lm = lim
    for i in range(mx,lmd+1,-(lmd-2)):
        lm += lm*0.01 
        low = mean - lm
        high = mean + lm
        newscr[i-lmd:i, x:x+lmd] = cv2.inRange(scr[i-lmd:i, x:x+lmd],low,high)
        
#         if(np.mean(mm)>=255):
#             print("ver",np.mean(mm))
        res = np.mean(scr[i-lmd:i, x:x+lmd]) 
        mean = np.array(mean)
        mean = cv2.addWeighted(res,0.5,mean,0.5,0)
#             newscr[i-lmd:i, x:x+lmd] = 255
#         else:
#             newscr[i-lmd:i, x:x+lmd] = 0   

In [12]:
import numpy as np
import pandas as pd
import time
import cv2
y=200
lim = 5
lmd = 5
clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
kernel = np.ones((3,3),np.uint8)
vrec = cv2.VideoCapture('v4.mp4',0)
kkk = 300
while(kkk):
    kkk-=1
    ret, scr = vrec.read()
while True:
#     scr = cv2.imread('18.png')

    ret, scr = vrec.read()
    scr = cv2.resize(scr, (680,480)) 
    shape = scr.shape
    newscr = np.zeros((shape[0],shape[1]),np.uint8)
    mx = shape[0]
    my = shape[1]//2
    # print(shape,mx,my)
    scr1 = scr 
    cv2.bilateralFilter(scr,70,30,100)
    scr = cv2.cvtColor(scr, cv2.COLOR_BGR2GRAY)
    # scr = clahe.apply(scr)
    mean = np.mean(scr[440:480,200:480]) 
    mean = np.uint8(mean)
    hor_rd(mean)

    newscr = cv2.morphologyEx(newscr,cv2.MORPH_OPEN,kernel, iterations = 1)
    newscr = cv2.morphologyEx(newscr,cv2.MORPH_CLOSE,kernel, iterations = 1)
    # newscr = cv2.morphologyEx(newscr,cv2.MORPH_OPEN,kernel, iterations = 1)
    # newscr = cv2.erode(newscr,kernel,iterations=1)
#     cv2.destroyAllWindows()
    cv2.imshow('scr',scr)
    # cv2.imshow('newscr',newscr)
    band =  cv2.bitwise_and(scr,scr,mask = newscr)

    cv2.imshow('blur',band)


    sure_bg = cv2.dilate(newscr,kernel,iterations=1)
            # Finding sure foreground area
    dist_transform = cv2.distanceTransform(newscr,cv2.DIST_L2,5)
    ret, sure_fg = cv2.threshold(dist_transform,0.0001*dist_transform.max(),255,0)
            # Finding unknown region
    sure_fg = np.uint8(sure_fg)
    unknown = cv2.subtract(sure_bg,sure_fg)
            # Marker labelling
    ret, markers = cv2.connectedComponents(sure_fg)
#     print(markers)
            # Add one to all labels so that sure background is not 0, but 1
    markers = markers+1
            # Now, mark the region of unknown with zero
    markers[unknown==255] = 0


    markers = cv2.watershed(scr,markers)
    scr[markers == -1] = [0,0,255]
    # print(markers)

    cv2.imshow('sure_fg',sure_fg)
    cv2.imshow('scr',scr)
    # cv2.imshow('sure_bg',sure_bg)
    


    q=cv2.waitKey(1)
    if q == 27:
        cv2.destroyAllWindows()

error: /Users/travis/build/skvark/opencv-python/opencv/modules/imgproc/src/segmentation.cpp:161: error: (-215) src.type() == (((0) & ((1 << 3) - 1)) + (((3)-1) << 3)) && dst.type() == (((4) & ((1 << 3) - 1)) + (((1)-1) << 3)) in function watershed


In [15]:
def crtr():
    def nothing(x):
        pass
    cv2.namedWindow(img)

    # create trackbars for color change
    cv2.createTrackbar('H',img,0,255,nothing)
    cv2.createTrackbar('S',img,0,255,nothing)
    cv2.createTrackbar('V',img,0,255,nothing)
    cv2.createTrackbar('H1',img,0,255,nothing)
    cv2.createTrackbar('S1',img,0,255,nothing)
    cv2.createTrackbar('V1',img,0,255,nothing)

In [16]:
import numpy as np
import pandas as pd
import time
import cv2
box = 5
st = 4
kernel = np.ones((3,3),np.uint8)
scr = cv2.imread('13.png')
scr = cv2.resize(scr, (680,480)) 
blur = cv2.bilateralFilter(scr,70,30,100)
hsv = cv2.cvtColor(blur, cv2.COLOR_BGR2HSV)
img = 'track'
crtr()
y,z = [np.mean(hsv[440:480,200:480, i]) for i in range(1,3)]


while True:
    a = cv2.getTrackbarPos('H',img)
    b = cv2.getTrackbarPos('S',img)
    c = cv2.getTrackbarPos('V',img)
    a1 = cv2.getTrackbarPos('H1',img)
    b1 = cv2.getTrackbarPos('S1',img)
    c1 = cv2.getTrackbarPos('V1',img)
#     a=27
#     b=20
#     c=20
#     x,y,z = [np.mean(hsv[440:480,200:480, i]) for i in range(3)]
    low = (np.uint8([0,y,z]) - [0,b,c])
    high = low + [180,2*b,2*c]
    print(low,high)
    mask = cv2.inRange(hsv,low,high)#np.uint8([a,b,c]),np.uint8([a1,b1,c1]))
    blur[440:480,200:480]=0
#     scr[mx-10:mx+1,my-8:my+3]=0
    # cv2.imshow('canny',canny)
#     cv2.imshow('src',scr)
    cv2.imshow('blur',blur)
    cv2.imshow('hsv',hsv)
    cv2.imshow('thresh',mask)


    q=cv2.waitKey(1)
    if q == 27:
    # time.sleep(30)
        cv2.destroyAllWindows()

[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]
[ 0 29 84] [180  29  84]


[  0 -35  60] [180  93 108]
[  0 -35 -13] [180  93 181]
[  0 -35 -64] [180  93 232]
[  0 -35 -79] [180  93 247]
[  0 -35 -80] [180  93 248]
[  0 -35 -80] [180  93 248]
[  0 -35 -80] [180  93 248]
[  0 -35 -80] [180  93 248]
[  0 -35 -80] [180  93 248]
[  0 -35 -80] [180  93 248]
[  0 -35 -80] [180  93 248]
[  0 -35 -80] [180  93 248]
[  0 -35 -80] [180  93 248]
[  0 -35 -80] [180  93 248]
[  0 -35 -80] [180  93 248]
[  0 -35 -80] [180  93 248]
[  0 -35 -80] [180  93 248]
[  0 -35 -75] [180  93 243]
[  0 -35 -75] [180  93 243]
[  0 -35 -65] [180  93 233]
[  0 -35 -59] [180  93 227]
[  0 -35 -58] [180  93 226]
[  0 -35 -54] [180  93 222]
[  0 -35 -51] [180  93 219]
[  0 -35 -46] [180  93 214]
[  0 -35 -45] [180  93 213]
[  0 -35 -42] [180  93 210]
[  0 -35 -40] [180  93 208]
[  0 -35 -40] [180  93 208]
[  0 -35 -39] [180  93 207]
[  0 -35 -38] [180  93 206]
[  0 -35 -36] [180  93 204]
[  0 -35 -35] [180  93 203]
[  0 -35 -34] [180  93 202]
[  0 -35 -30] [180  93 198]
[  0 -35 -30] [180  

[ 0 -1 40] [180  59 128]
[ 0 -1 40] [180  59 128]
[ 0 -1 40] [180  59 128]
[ 0  1 40] [180  57 128]
[ 0  1 40] [180  57 128]
[ 0  3 40] [180  55 128]
[ 0  4 40] [180  54 128]
[ 0  4 40] [180  54 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  5 40] [180  53 128]
[ 0  6 40] [180  52 128]
[ 0  6 40] [180  52 128]
[ 0  6 40] [180  52 128]
[ 0  6 40] [180  52 128]
[ 0  6 40] [180  52 128]
[ 0  6 40] [180  52 128]
[ 0  6 40] [180  52 128]
[ 0  6 40] [180  52 128]
[ 0  6 40] [180  52 128]
[ 0  6 40] [180  52 128]
[ 0  6 40] [180  52 128]
[ 0  6 40] [180  52 128]


[ 0 -4 40] [180  62 128]
[ 0 -4 40] [180  62 128]
[ 0 -4 40] [180  62 128]
[ 0 -4 40] [180  62 128]
[ 0 -4 40] [180  62 128]
[ 0 -4 40] [180  62 128]
[ 0 -4 40] [180  62 128]
[ 0 -4 40] [180  62 128]
[ 0 -4 40] [180  62 128]
[ 0 -4 40] [180  62 128]
[ 0 -4 42] [180  62 126]
[ 0 -4 42] [180  62 126]
[ 0 -4 42] [180  62 126]
[ 0 -4 42] [180  62 126]
[ 0 -4 42] [180  62 126]
[ 0 -4 42] [180  62 126]
[ 0 -4 42] [180  62 126]
[ 0 -4 42] [180  62 126]
[ 0 -4 43] [180  62 125]
[ 0 -4 41] [180  62 127]
[ 0 -4 40] [180  62 128]
[ 0 -4 39] [180  62 129]
[ 0 -4 39] [180  62 129]
[ 0 -4 36] [180  62 132]
[ 0 -4 36] [180  62 132]
[ 0 -4 33] [180  62 135]
[ 0 -4 31] [180  62 137]
[ 0 -4 30] [180  62 138]
[ 0 -4 30] [180  62 138]
[ 0 -4 30] [180  62 138]
[ 0 -4 30] [180  62 138]
[ 0 -4 30] [180  62 138]
[ 0 -4 30] [180  62 138]
[ 0 -4 30] [180  62 138]
[ 0 -4 30] [180  62 138]
[ 0 -4 30] [180  62 138]
[ 0 -4 30] [180  62 138]
[ 0 -4 30] [180  62 138]
[ 0 -4 30] [180  62 138]
[ 0 -4 32] [180  62 136]


[   0 -154   59] [180 212 109]
[   0 -154   59] [180 212 109]
[   0 -154   59] [180 212 109]
[   0 -154   59] [180 212 109]
[   0 -154   59] [180 212 109]
[   0 -154   59] [180 212 109]
[   0 -154   59] [180 212 109]
[   0 -154   59] [180 212 109]
[   0 -154   59] [180 212 109]
[   0 -154   59] [180 212 109]
[   0 -154   59] [180 212 109]
[   0 -154   59] [180 212 109]
[   0 -154   59] [180 212 109]
[   0 -154   59] [180 212 109]
[   0 -153   59] [180 211 109]
[   0 -151   59] [180 209 109]
[   0 -151   59] [180 209 109]
[   0 -142   59] [180 200 109]
[   0 -134   59] [180 192 109]
[   0 -119   59] [180 177 109]
[   0 -102   59] [180 160 109]
[  0 -89  59] [180 147 109]
[  0 -89  59] [180 147 109]
[  0 -79  59] [180 137 109]
[  0 -70  59] [180 128 109]
[  0 -70  59] [180 128 109]
[  0 -68  59] [180 126 109]
[  0 -66  59] [180 124 109]
[  0 -62  59] [180 120 109]
[  0 -62  59] [180 120 109]
[  0 -62  59] [180 120 109]
[  0 -68  59] [180 126 109]
[  0 -69  59] [180 127 109]
[  0 -82  59]

[   0 -125   54] [180 183 114]
[   0 -125   54] [180 183 114]
[   0 -125   54] [180 183 114]
[   0 -125   54] [180 183 114]
[   0 -125   54] [180 183 114]
[   0 -125   54] [180 183 114]
[   0 -125   54] [180 183 114]
[   0 -125   54] [180 183 114]
[   0 -125   54] [180 183 114]
[   0 -125   54] [180 183 114]
[   0 -125   54] [180 183 114]
[   0 -125   54] [180 183 114]
[   0 -125   53] [180 183 115]
[   0 -125   52] [180 183 116]
[   0 -125   49] [180 183 119]
[   0 -125   47] [180 183 121]
[   0 -125   47] [180 183 121]
[   0 -125   47] [180 183 121]
[   0 -125   47] [180 183 121]
[   0 -125   47] [180 183 121]
[   0 -125   47] [180 183 121]
[   0 -125   47] [180 183 121]
[   0 -125   47] [180 183 121]
[   0 -125   47] [180 183 121]
[   0 -125   47] [180 183 121]
[   0 -125   47] [180 183 121]
[   0 -125   47] [180 183 121]
[   0 -125   47] [180 183 121]
[   0 -125   48] [180 183 120]
[   0 -125   48] [180 183 120]
[   0 -125   50] [180 183 118]
[   0 -125   50] [180 183 118]
[   0 -1

[   0 -125   67] [180 183 101]
[   0 -125   67] [180 183 101]
[   0 -125   67] [180 183 101]
[   0 -125   67] [180 183 101]
[   0 -125   67] [180 183 101]
[   0 -125   67] [180 183 101]
[   0 -125   67] [180 183 101]
[   0 -125   67] [180 183 101]
[   0 -125   67] [180 183 101]
[   0 -125   67] [180 183 101]
[   0 -125   67] [180 183 101]
[   0 -125   67] [180 183 101]
[   0 -125   66] [180 183 102]
[   0 -125   66] [180 183 102]
[   0 -125   66] [180 183 102]
[   0 -125   64] [180 183 104]
[   0 -125   64] [180 183 104]
[   0 -125   63] [180 183 105]
[   0 -125   61] [180 183 107]
[   0 -125   61] [180 183 107]
[   0 -125   61] [180 183 107]
[   0 -125   61] [180 183 107]
[   0 -125   61] [180 183 107]
[   0 -125   61] [180 183 107]
[   0 -125   61] [180 183 107]
[   0 -125   61] [180 183 107]
[   0 -125   61] [180 183 107]
[   0 -125   61] [180 183 107]
[   0 -125   61] [180 183 107]
[   0 -125   61] [180 183 107]
[   0 -125   61] [180 183 107]
[   0 -125   61] [180 183 107]
[   0 -1

[ 0  0 61] [180  58 107]
[ 0  0 61] [180  58 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]
[ 0 -1 61] [180  59 107]


[  0  -1 -97] [180  59 265]
[  0  -1 -96] [180  59 264]
[  0  -1 -95] [180  59 263]
[  0  -1 -95] [180  59 263]
[  0  -1 -95] [180  59 263]
[  0  -1 -94] [180  59 262]
[  0  -1 -94] [180  59 262]
[  0  -1 -94] [180  59 262]
[  0  -1 -93] [180  59 261]
[  0  -1 -93] [180  59 261]
[  0  -1 -93] [180  59 261]
[  0  -1 -92] [180  59 260]
[  0  -1 -92] [180  59 260]
[  0  -1 -91] [180  59 259]
[  0  -1 -91] [180  59 259]
[  0  -1 -91] [180  59 259]
[  0  -1 -89] [180  59 257]
[  0  -1 -87] [180  59 255]
[  0  -1 -83] [180  59 251]
[  0  -1 -83] [180  59 251]
[  0  -1 -79] [180  59 247]
[  0  -1 -76] [180  59 244]
[  0  -1 -74] [180  59 242]
[  0  -1 -74] [180  59 242]
[  0  -1 -74] [180  59 242]
[  0  -1 -74] [180  59 242]
[  0  -1 -74] [180  59 242]
[  0  -1 -74] [180  59 242]
[  0  -1 -74] [180  59 242]
[  0  -1 -74] [180  59 242]
[  0  -1 -74] [180  59 242]
[  0  -1 -74] [180  59 242]
[  0  -1 -74] [180  59 242]
[  0  -1 -69] [180  59 237]
[  0  -1 -67] [180  59 235]
[  0  -1 -58] [180  

[ 0 -1 15] [180  59 153]
[ 0 -1 15] [180  59 153]
[ 0 -1 15] [180  59 153]
[ 0 -1 15] [180  59 153]
[ 0 -1 15] [180  59 153]
[ 0 -1 15] [180  59 153]
[ 0 -1 16] [180  59 152]
[ 0 -1 16] [180  59 152]
[ 0 -1 26] [180  59 142]
[ 0 -1 29] [180  59 139]
[ 0 -1 29] [180  59 139]
[ 0 -1 30] [180  59 138]
[ 0 -1 30] [180  59 138]
[ 0 -1 30] [180  59 138]
[ 0 -1 30] [180  59 138]
[ 0 -1 30] [180  59 138]
[ 0 -1 30] [180  59 138]
[ 0 -1 30] [180  59 138]
[ 0 -1 30] [180  59 138]
[ 0 -1 30] [180  59 138]
[ 0 -1 30] [180  59 138]
[ 0 -1 30] [180  59 138]
[ 0 -1 30] [180  59 138]
[ 0 -1 30] [180  59 138]
[ 0 -1 30] [180  59 138]
[ 0 -1 30] [180  59 138]
[ 0 -1 30] [180  59 138]
[ 0 -1 30] [180  59 138]
[ 0 -1 30] [180  59 138]
[ 0 -1 29] [180  59 139]
[ 0 -1 29] [180  59 139]
[ 0 -1 27] [180  59 141]
[ 0 -1 27] [180  59 141]
[ 0 -1 26] [180  59 142]
[ 0 -1 26] [180  59 142]
[ 0 -1 26] [180  59 142]
[ 0 -1 26] [180  59 142]
[ 0 -1 26] [180  59 142]
[ 0 -1 26] [180  59 142]
[ 0 -1 26] [180  59 142]


[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]
[ 0 -1 39] [180  59 129]


[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -218   39] [180 276 129]
[   0 -2

[   0 -218   54] [180 276 114]
[   0 -218   54] [180 276 114]
[   0 -218   54] [180 276 114]
[   0 -218   54] [180 276 114]
[   0 -218   56] [180 276 112]
[   0 -218   57] [180 276 111]
[   0 -218   57] [180 276 111]
[   0 -218   57] [180 276 111]
[   0 -218   57] [180 276 111]
[   0 -218   57] [180 276 111]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -218   58] [180 276 110]
[   0 -2

[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -218   60] [180 276 108]
[   0 -2

error: /Users/travis/build/skvark/opencv-python/opencv/modules/highgui/src/window_QT.cpp:445: error: (-27) NULL window handler in function icvFindTrackBarByName


In [28]:
def crtr():
    def nothing(x):
        pass
    cv2.namedWindow(img)

    # create trackbars for color change
    cv2.createTrackbar('H',img,0,255,nothing)
    cv2.createTrackbar('S',img,0,255,nothing)
    cv2.createTrackbar('V',img,0,255,nothing)
    cv2.createTrackbar('H1',img,0,255,nothing)
    cv2.createTrackbar('S1',img,0,255,nothing)
    cv2.createTrackbar('V1',img,0,255,nothing)

In [ ]:
import numpy as np
import pandas as pd
import time
import cv2
box = 5
st = 4
kernel = np.ones((3,3),np.uint8)
scr = cv2.imread('18.png')
scr = cv2.resize(scr, (680,480)) 
blur = cv2.bilateralFilter(scr,70,30,100)
gray = cv2.cvtColor(scr, cv2.COLOR_BGR2GRAY)
img = 'track'
crtr()
gray = clahe.apply(gray)
x = np.mean(gray[440:480,200:480])


while True:
    a = cv2.getTrackbarPos('H',img)
    b = cv2.getTrackbarPos('S',img)
    c = cv2.getTrackbarPos('V',img)
    a1 = cv2.getTrackbarPos('H1',img)
    b1 = cv2.getTrackbarPos('S1',img)
    c1 = cv2.getTrackbarPos('V1',img)
    low = x-a
    high = x+a
    mask = cv2.inRange(gray,low,high)#np.uint8([a,b,c]),np.uint8([a1,b1,c1]))
#     blur[440:480,200:480]=0
#     scr[mx-10:mx+1,my-8:my+3]=0
    # cv2.imshow('canny',canny)
#     cv2.imshow('src',scr)
#     cv2.imshow('blur',blur)
    cv2.imshow('hsv',gray)
    cv2.imshow('thresh',mask)


    q=cv2.waitKey(1)
    if q == 27:
    # time.sleep(30)
        cv2.destroyAllWindows()

In [6]:
from sklearn.cluster import KMeans
import numpy as np
X = np.array([[1, 2], [1, 4], [1, 0],
              [4, 2], [4, 4], [4, 0]])
kmeans = KMeans(n_clusters=2, random_state=0).fit(X)
# kmeans.labels_

kmeans.predict([[0, 0], [4, 4]])

# kmeans.cluster_centers_

array([0, 1], dtype=int32)

In [21]:
a=set([1,2,3,4,5,6])
b=set([6,7,8,9])
if a.intersection(b):
    print(a)

{1, 2, 3, 4, 5, 6}
