In [4]:
import numpy as np
import pandas as pd
import time
import cv2

In [5]:
# ker = np.array([[0,0,3,2,2,2,3,0,0],[0,2,3,5,5,5,3,2,0],[3,3,5,3,0,3,5,3,3],[2,5,3,-12,-23,-12,3,5,2],[2,5,0,-23,-40,-23,0,5,2],[2,5,3,-12,-23,-12,3,5,2],[3,3,5,3,0,3,5,3,3],[0,2,3,5,5,5,3,2,0],[0,0,3,2,2,2,3,0,0]])
ker1 = []
ker1=[[-x,-x,-x,-x,-x,-x,-x,-x,-x] for x in range(1,5)]
x=0
ker1.append([x,x,x,x,x,x,x,x,x])
ker1=ker1+[[x,x,x,x,x,x,x,x,x] for x in range(4,0,-1)]
ker1 = np.array(ker1)
ker1.shape
ker2 = ker1.transpose()
thr = [y,y,y]
newscr = np.zeros((shape[0],shape[1]),np.uint8)
# s256 = np.zeros((9,9),np.uint8) + 255
# print(s256)
# cv2.imshow('ii',s256)
# time.sleep(5)
# q=cv2.waitKey(1)
# if q == 27:
#     cv2.destroyAllWindows()

In [6]:
# print(ker2)

In [7]:
# print(scr[mx-9:mx+1, my:my+9,0])
# res = [scr[mx-9:mx+1, my:my+9,0]*ker2 ]
# print(res)

In [11]:
def hor_rd():
    for i in range(my,shape[1]-9,7):
#         print(np.array(scr[mx-9:mx+1, i:i+9,0]).shape)
        res1 = abs(np.array([np.sum(scr[mx-9:mx+1, i:i+9,j] * ker1) for j in range(3)]))
        res2 = abs(np.array([np.sum(scr[mx-9:mx+1, i:i+9,j] * ker2) for j in range(3)]))
        print(res1,res2)
        print("hor",i)
        if((res1[0]>thr[0] or res1[1]>thr[1] or res1[2]>thr[2]) or (res2[0]>thr[0] or res2[1]>thr[1] or res2[2]>thr[2])):
            newscr[mx-7:mx+1-2, i+2:i+9-2] = 0
#             break
        else:
            
            newscr[mx-9:mx+1, my+2:my+i] = 255
            ver_rd(i)
    for i in range(my,10, -7):
        res1 = abs(np.array([np.sum(scr[mx-9:mx+1, i-9:i,j] * ker1) for j in range(3)]))
        res2 = abs(np.array([np.sum(scr[mx-9:mx+1, i-9:i,j] * ker2) for j in range(3)]))
        print("hor",i)
        if((res1[0]>thr[0] or res1[1]>thr[1] or res1[2]>thr[2]) or (res2[0]>thr[0] or res2[1]>thr[1] or res2[2]>thr[2])):
            newscr[mx-9+2:mx+1-2, i-9+2:i-2] = 0
#             break
        else:
            newscr[mx-9:mx+1, i-9+2:i] = 255
            ver_rd(i-10)

In [12]:
def ver_rd(x):
    for i in range(mx,10,-7):
        res1 = abs(np.array([np.sum(scr[i-9:i, x:x+9,j] * ker1) for j in range(3)]))
        res2 = abs(np.array([np.sum(scr[i-9:i, x:x+9,j] * ker2) for j in range(3)]))
        print("ver",i)
        if((res1[0]>thr[0] or res1[1]>thr[1] or res1[2]>thr[2]) or (res2[0]>thr[0] or res2[1]>thr[1] or res2[2]>thr[2])):
            newscr[i-9+2:i-2, x+2:x+9-2] = 0
#             break
        else:
            newscr[i-9:i, x:x+9] = 255

In [13]:
import numpy as np
import pandas as pd
import time
import cv2
cv2.destroyAllWindows()
y=200
thr = [y,y,y]
scr = cv2.imread('11.png')
scr = cv2.resize(scr, (680,480)) 
shape = scr.shape
mx = shape[0]
my = shape[1]//2
print(shape,mx,my)
scr = cv2.bilateralFilter(scr,70,30,100)
# scr = cv2.cvtColor(blur, cv2.COLOR_BGR2HSV)
hor_rd()
# x,y,z = [np.mean(blur[440:480,200:480, i]) for i in range(3)]
# a = np.mean(gray[440:480,200:480]) 
# # print(x,y,z)
# low = np.uint8([x,y,z]) - 30
# high = np.uint8([x,y,z]) + 30
# mask = cv2.inRange(blur,low,high)
cv2.imshow('scr',scr)
# cv2.imshow('newscr',newscr)
band =  cv2.bitwise_and(scr,scr,mask = newscr)
# canny = cv2.Canny(scr,50,100)

cv2.imshow('blur',band)
# cv2.imshow('thresh',mask)
# cv2.imshow('canny',canny)
# scr[440:480,200:480]=0
q=cv2.waitKey(1)
if q == 27:
    cv2.destroyAllWindows()

(480, 680, 3) 480 340
[0 0 0] [0 0 0]
hor 340
ver 480
ver 473
ver 466
ver 459
ver 452
ver 445
ver 438
ver 431
ver 424
ver 417
ver 410
ver 403
ver 396
ver 389
ver 382
ver 375
ver 368
ver 361
ver 354
ver 347
ver 340
ver 333
ver 326
ver 319
ver 312
ver 305
ver 298
ver 291
ver 284
ver 277
ver 270
ver 263
ver 256
ver 249
ver 242
ver 235
ver 228
ver 221
ver 214
ver 207
ver 200
ver 193
ver 186
ver 179
ver 172
ver 165
ver 158
ver 151
ver 144
ver 137
ver 130
ver 123
ver 116
ver 109
ver 102
ver 95
ver 88
ver 81
ver 74
ver 67
ver 60
ver 53
ver 46
ver 39
ver 32
ver 25
ver 18
ver 11
[0 0 0] [0 0 0]
hor 347
ver 480
ver 473
ver 466
ver 459
ver 452
ver 445
ver 438
ver 431
ver 424
ver 417
ver 410
ver 403
ver 396
ver 389
ver 382
ver 375
ver 368
ver 361
ver 354
ver 347
ver 340
ver 333
ver 326
ver 319
ver 312
ver 305
ver 298
ver 291
ver 284
ver 277
ver 270
ver 263
ver 256
ver 249
ver 242
ver 235
ver 228
ver 221
ver 214
ver 207
ver 200
ver 193
ver 186
ver 179
ver 172
ver 165
ver 158
ver 151
ver 144
ver 137

ver 95
ver 88
ver 81
ver 74
ver 67
ver 60
ver 53
ver 46
ver 39
ver 32
ver 25
ver 18
ver 11
[6 4 5] [ 82  89 132]
hor 445
ver 480
ver 473
ver 466
ver 459
ver 452
ver 445
ver 438
ver 431
ver 424
ver 417
ver 410
ver 403
ver 396
ver 389
ver 382
ver 375
ver 368
ver 361
ver 354
ver 347
ver 340
ver 333
ver 326
ver 319
ver 312
ver 305
ver 298
ver 291
ver 284
ver 277
ver 270
ver 263
ver 256
ver 249
ver 242
ver 235
ver 228
ver 221
ver 214
ver 207
ver 200
ver 193
ver 186
ver 179
ver 172
ver 165
ver 158
ver 151
ver 144
ver 137
ver 130
ver 123
ver 116
ver 109
ver 102
ver 95
ver 88
ver 81
ver 74
ver 67
ver 60
ver 53
ver 46
ver 39
ver 32
ver 25
ver 18
ver 11
[ 8  7 38] [ 4  6 45]
hor 452
ver 480
ver 473
ver 466
ver 459
ver 452
ver 445
ver 438
ver 431
ver 424
ver 417
ver 410
ver 403
ver 396
ver 389
ver 382
ver 375
ver 368
ver 361
ver 354
ver 347
ver 340
ver 333
ver 326
ver 319
ver 312
ver 305
ver 298
ver 291
ver 284
ver 277
ver 270
ver 263
ver 256
ver 249
ver 242
ver 235
ver 228
ver 221
ver 214
ver 20

ver 39
ver 32
ver 25
ver 18
ver 11
[39 73 39] [37  7  2]
hor 564
ver 480
ver 473
ver 466
ver 459
ver 452
ver 445
ver 438
ver 431
ver 424
ver 417
ver 410
ver 403
ver 396
ver 389
ver 382
ver 375
ver 368
ver 361
ver 354
ver 347
ver 340
ver 333
ver 326
ver 319
ver 312
ver 305
ver 298
ver 291
ver 284
ver 277
ver 270
ver 263
ver 256
ver 249
ver 242
ver 235
ver 228
ver 221
ver 214
ver 207
ver 200
ver 193
ver 186
ver 179
ver 172
ver 165
ver 158
ver 151
ver 144
ver 137
ver 130
ver 123
ver 116
ver 109
ver 102
ver 95
ver 88
ver 81
ver 74
ver 67
ver 60
ver 53
ver 46
ver 39
ver 32
ver 25
ver 18
ver 11
[12 24 31] [ 6 23 19]
hor 571
ver 480
ver 473
ver 466
ver 459
ver 452
ver 445
ver 438
ver 431
ver 424
ver 417
ver 410
ver 403
ver 396
ver 389
ver 382
ver 375
ver 368
ver 361
ver 354
ver 347
ver 340
ver 333
ver 326
ver 319
ver 312
ver 305
ver 298
ver 291
ver 284
ver 277
ver 270
ver 263
ver 256
ver 249
ver 242
ver 235
ver 228
ver 221
ver 214
ver 207
ver 200
ver 193
ver 186
ver 179
ver 172
ver 165
ver 15

ver 375
ver 368
ver 361
ver 354
ver 347
ver 340
ver 333
ver 326
ver 319
ver 312
ver 305
ver 298
ver 291
ver 284
ver 277
ver 270
ver 263
ver 256
ver 249
ver 242
ver 235
ver 228
ver 221
ver 214
ver 207
ver 200
ver 193
ver 186
ver 179
ver 172
ver 165
ver 158
ver 151
ver 144
ver 137
ver 130
ver 123
ver 116
ver 109
ver 102
ver 95
ver 88
ver 81
ver 74
ver 67
ver 60
ver 53
ver 46
ver 39
ver 32
ver 25
ver 18
ver 11
hor 333
ver 480
ver 473
ver 466
ver 459
ver 452
ver 445
ver 438
ver 431
ver 424
ver 417
ver 410
ver 403
ver 396
ver 389
ver 382
ver 375
ver 368
ver 361
ver 354
ver 347
ver 340
ver 333
ver 326
ver 319
ver 312
ver 305
ver 298
ver 291
ver 284
ver 277
ver 270
ver 263
ver 256
ver 249
ver 242
ver 235
ver 228
ver 221
ver 214
ver 207
ver 200
ver 193
ver 186
ver 179
ver 172
ver 165
ver 158
ver 151
ver 144
ver 137
ver 130
ver 123
ver 116
ver 109
ver 102
ver 95
ver 88
ver 81
ver 74
ver 67
ver 60
ver 53
ver 46
ver 39
ver 32
ver 25
ver 18
ver 11
hor 326
ver 480
ver 473
ver 466
ver 459
ver 452
ve

ver 165
ver 158
ver 151
ver 144
ver 137
ver 130
ver 123
ver 116
ver 109
ver 102
ver 95
ver 88
ver 81
ver 74
ver 67
ver 60
ver 53
ver 46
ver 39
ver 32
ver 25
ver 18
ver 11
hor 179
ver 480
ver 473
ver 466
ver 459
ver 452
ver 445
ver 438
ver 431
ver 424
ver 417
ver 410
ver 403
ver 396
ver 389
ver 382
ver 375
ver 368
ver 361
ver 354
ver 347
ver 340
ver 333
ver 326
ver 319
ver 312
ver 305
ver 298
ver 291
ver 284
ver 277
ver 270
ver 263
ver 256
ver 249
ver 242
ver 235
ver 228
ver 221
ver 214
ver 207
ver 200
ver 193
ver 186
ver 179
ver 172
ver 165
ver 158
ver 151
ver 144
ver 137
ver 130
ver 123
ver 116
ver 109
ver 102
ver 95
ver 88
ver 81
ver 74
ver 67
ver 60
ver 53
ver 46
ver 39
ver 32
ver 25
ver 18
ver 11
hor 172
ver 480
ver 473
ver 466
ver 459
ver 452
ver 445
ver 438
ver 431
ver 424
ver 417
ver 410
ver 403
ver 396
ver 389
ver 382
ver 375
ver 368
ver 361
ver 354
ver 347
ver 340
ver 333
ver 326
ver 319
ver 312
ver 305
ver 298
ver 291
ver 284
ver 277
ver 270
ver 263
ver 256
ver 249
ver 242
ve

ver 81
ver 74
ver 67
ver 60
ver 53
ver 46
ver 39
ver 32
ver 25
ver 18
ver 11
hor 60
ver 480
ver 473
ver 466
ver 459
ver 452
ver 445
ver 438
ver 431
ver 424
ver 417
ver 410
ver 403
ver 396
ver 389
ver 382
ver 375
ver 368
ver 361
ver 354
ver 347
ver 340
ver 333
ver 326
ver 319
ver 312
ver 305
ver 298
ver 291
ver 284
ver 277
ver 270
ver 263
ver 256
ver 249
ver 242
ver 235
ver 228
ver 221
ver 214
ver 207
ver 200
ver 193
ver 186
ver 179
ver 172
ver 165
ver 158
ver 151
ver 144
ver 137
ver 130
ver 123
ver 116
ver 109
ver 102
ver 95
ver 88
ver 81
ver 74
ver 67
ver 60
ver 53
ver 46
ver 39
ver 32
ver 25
ver 18
ver 11
hor 53
ver 480
ver 473
ver 466
ver 459
ver 452
ver 445
ver 438
ver 431
ver 424
ver 417
ver 410
ver 403
ver 396
ver 389
ver 382
ver 375
ver 368
ver 361
ver 354
ver 347
ver 340
ver 333
ver 326
ver 319
ver 312
ver 305
ver 298
ver 291
ver 284
ver 277
ver 270
ver 263
ver 256
ver 249
ver 242
ver 235
ver 228
ver 221
ver 214
ver 207
ver 200
ver 193
ver 186
ver 179
ver 172
ver 165
ver 158
ve

In [14]:
print(newscr)

[[  0   0   0 ...,   0   0   0]
 [  0   0   0 ...,   0   0   0]
 [  0 255 255 ..., 255   0   0]
 ..., 
 [  0 255 255 ..., 255 255 255]
 [  0 255 255 ..., 255 255 255]
 [  0 255 255 ..., 255 255 255]]


In [26]:
for i,j in zip(range(480-box),range(680-box)):
    m = np.mean(scr[i:i+box,j:j+box])
    n = np.mean(scr[i:i+box,j:j+box])
    

NameError: name 'box' is not defined

In [7]:
def crtr():
    def nothing(x):
        pass
    cv2.namedWindow(img)

    # create trackbars for color change
    cv2.createTrackbar('H',img,0,255,nothing)
    cv2.createTrackbar('S',img,0,255,nothing)
    cv2.createTrackbar('V',img,0,255,nothing)
    cv2.createTrackbar('H1',img,0,255,nothing)
    cv2.createTrackbar('S1',img,0,255,nothing)
    cv2.createTrackbar('V1',img,0,255,nothing)

In [58]:
import numpy as np
import pandas as pd
import time
import cv2
box = 5
st = 4

scr = cv2.imread('13.png')
scr = cv2.resize(scr, (680,480)) 
blur = cv2.bilateralFilter(scr,70,30,100)
hsv = cv2.cvtColor(blur, cv2.COLOR_BGR2HSV)
img = 'track'
crtr()
y,z = [np.mean(hsv[440:480,200:480, i]) for i in range(1,3)]


while True:
    a = cv2.getTrackbarPos('H',img)
    b = cv2.getTrackbarPos('S',img)
    c = cv2.getTrackbarPos('V',img)
    a1 = cv2.getTrackbarPos('H1',img)
    b1 = cv2.getTrackbarPos('S1',img)
    c1 = cv2.getTrackbarPos('V1',img)
#     a=27
#     b=20
#     c=20
#     x,y,z = [np.mean(hsv[440:480,200:480, i]) for i in range(3)]
    low = (np.uint8([0,y,z]) - [0,b,c])
    high = low + [180,2*b,2*c]
    print(low,high)
    mask = cv2.inRange(hsv,low,high)#np.uint8([a,b,c]),np.uint8([a1,b1,c1]))
    blur[440:480,200:480]=0
#     scr[mx-10:mx+1,my-8:my+3]=0
    # cv2.imshow('canny',canny)
#     cv2.imshow('src',scr)
    cv2.imshow('blur',blur)
    cv2.imshow('hsv',hsv)
    cv2.imshow('thresh',mask)


    q=cv2.waitKey(1)
    if q == 27:
    # time.sleep(30)
        cv2.destroyAllWindows()

NameError: name 'crtr' is not defined

In [63]:
print(a,b,c,a1,b1,c1)

80 76 83 137 127 127


In [18]:
import numpy as np
if(all(np.array([0,0,0])-np.array([18,106,28]))):
    print("uyp")

uyp


In [ ]:
q=0
road_mn = 100
kernel = np.ones((3,3),np.uint8)
while True:
    vrec = cv2.VideoCapture('v2.mp4',0)
    while True:
        w=0;
        ret, scr = vrec.read()
        if not ret:
            break
#         time.sleep()

        gray = cv2.cvtColor(scr, cv2.COLOR_BGR2GRAY)
        hls = cv2.cvtColor(scr, cv2.COLOR_BGR2HLS)
        hsv = cv2.cvtColor(scr, cv2.COLOR_BGR2HSV)
#         scr = cv2.bilateralFilter(scr,40,100,100)
        x,y,z = [np.mean(scr[335:355,160:460, i]) for i in range(3)]
        low = np.uint8([x,y,z]) - 20
        high = np.uint8([x,y,z]) + 20
        mask = cv2.inRange(scr,low,high)
        morp = cv2.morphologyEx(mask,cv2.MORPH_OPEN,kernel, iterations = 3)
#         can = cv2.Canny(morp, 0, 255)
        
#         h1, h2, h3 = [np.min(hsv[335:355,160:460, i]) for i in range(3)]
#         g1, g2, g3 = [np.max(hsv[335:355,160:460, i]) for i in range(3)]
#         low1 = np.uint8([h1, h2, h3])
#         high1 = np.uint8([g1, g2, g3])
#         mask2 = cv2.inRange(hls,low1,high1)
#         close = cv2.morphologyEx(mask,cv2.MORPH_CLOSE,kernel, iterations = 1)
#         close = cv2.erode(close,kernel,iterations=3)
        cv2.imshow('scr1',scr)
        cv2.imshow('scr11',mask) 
#         cv2.imshow('hls',hls)
        cv2.imshow('mask1',can)
        cv2.imshow('morp',morp)
#         cv2.imshow('mask2',mask2)
        
        
#         cv2.imshow('close',close)
        #75 365  405 365 75 265 405 265
        q = cv2.waitKey(1)
        if q == 27:
            cv2.destroyAllWindows()
            break
    if q == 27:
            cv2.destroyAllWindows()
            break
cv2.destroyAllWindows()

In [32]:
q=0
road_mn = 100
kernel = np.ones((5,5),np.uint8)
clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8,8))
while True:
    vrec = cv2.VideoCapture('v2.mp4',0)
    while True:
        ret, scr = vrec.read()
        if not ret:
            break
        time.sleep(.03)
        gray = cv2.cvtColor(scr, cv2.COLOR_BGR2GRAY)
        hls = cv2.cvtColor(scr, cv2.COLOR_BGR2HLS)
        hsv = cv2.cvtColor(scr, cv2.COLOR_BGR2HSV)
        scr = cv2.bilateralFilter(scr,40,75,75)
        
        x,y,z = [np.min(hls[335:355,160:460, i]) for i in range(3)]
        low = np.uint8([x,y,z]) * [1,0,1]
        high = low + [0,255,0]
        mask = cv2.inRange(hls, np.uint8([x,y,z]), np.uint8([x1,y1,z1]))

        cv2.imshow('scr1',scr)
        cv2.imshow('scr11',mask)
#         cv2.imshow('scr111',can)
#         cv2.imshow('scr1111',sure_fg)

        cv2.imshow('scr2',gray)
        cv2.imshow('hls',hls)
        cv2.imshow('hsv',hsv)
#         hsv[335:355,160:460]=higher_path
#         cv2.imshow('scr3',hsv)
#         cv2.imshow('scr4',res)
        
        #75 365  405 365 75 265 405 265
        q = cv2.waitKey(1)
        if q == 27:
            cv2.destroyAllWindows()
            break
    if q == 27:
            cv2.destroyAllWindows()
            break
cv2.destroyAllWindows()

In [38]:
        kernel = np.ones((5,5),np.uint8)
        ret, thresh = cv2.threshold(gray,0,255,cv2.THRESH_BINARY_INV)
        opening = cv2.morphologyEx(thresh,cv2.MORPH_OPEN,kernel, iterations = 2)
        # sure background area
        sure_bg = cv2.dilate(opening,kernel,iterations=3)
        # Finding sure foreground area
        dist_transform = cv2.distanceTransform(opening,cv2.DIST_L2,5)
        ret, sure_fg = cv2.threshold(dist_transform,0.7*dist_transform.max(),255,0)
        # Finding unknown region
        sure_fg = np.uint8(sure_fg)
        unknown = cv2.subtract(sure_bg,sure_fg)
        # Marker labelling
        ret, markers = cv2.connectedComponents(sure_fg)
        # Add one to all labels so that sure background is not 0, but 1
        markers = markers+1
        # Now, mark the region of unknown with zero
        markers[unknown==255] = 0
        markers = cv2.watershed(scr,markers)
        scr[markers == -1] = [255,0,0]
        cv2.imshow('scr1',scr)
#         scr = cv2.bilateralFilter(scr,9,75,75)
#         scr1 = cv2.morphologyEx(scr, cv2.MORPH_OPEN, kernel)
#         scr1 = cv2.morphologyEx(scr1, cv2.MORPH_CLOSE, kernel)
#         scr11 = cv2.morphologyEx(scr, cv2.MORPH_CLOSE, kernel)
#         scr11 = cv2.morphologyEx(scr11, cv2.MORPH_OPEN, kernel)
#         erosion = cv2.erode(scr,kernel,iterations = 1)
        
#         gray = cv2.cvtColor(scr, cv2.COLOR_BGR2GRAY)
#         hsv = cv2.cvtColor(scr, cv2.COLOR_BGR2HSV)
#         x,y,z =[ np.min(scr[335:355,160:460,i]) for i in range(3)]#,np.mean(scr[75:406, 265:366, 1],dtype='int'),np.mean(scr[75:406, 265:366, 2],dtype='int')
#         x1,y1,z1 =[ np.max(scr[335:355,160:460,i]) for i in range(3)]
#         lower_path = cv2.cvtColor(np.uint8([[[x,y,z]]]),cv2.COLOR_BGR2HSV)
#         higher_path = cv2.cvtColor(np.uint8([[[x1,y1,z1]]]),cv2.COLOR_BGR2HSV)
#         mask = cv2.inRange(hsv,lower_path,higher_path)
#         res = cv2.bitwise_and(scr,scr, mask= mask)

In [ ]:
import numpy as np
import pandas as pd
import time
import cv2
scr = cv2.imread('17.png')
scr = cv2.resize(scr, (680,480)) 
shape = scr.shape
mx = shape[0]
my = shape[1]//2
print(shape,mx,my)
scr[mx-10:mx+1,my-8:my+3]=0
gray = cv2.cvtColor(scr, cv2.COLOR_BGR2GRAY)
# cv2.imshow('canny',canny)
cv2.imshow('src',scr)
kernel = np.ones((5,5),np.uint8)
x,y,z = [np.mean(scr[440:480,200:480, i]) for i in range(3)]
low = np.uint8([x,y,z]) - 40
high = np.uint8([x,y,z]) + 40
thresh = cv2.inRange(scr,low,high)
opening = cv2.morphologyEx(thresh,cv2.MORPH_OPEN,kernel, iterations = 2)
        # sure background area
sure_bg = cv2.dilate(opening,kernel,iterations=3)
        # Finding sure foreground area
dist_transform = cv2.distanceTransform(opening,cv2.DIST_L2,5)
ret, sure_fg = cv2.threshold(dist_transform,0.0001*dist_transform.max(),255,0)
        # Finding unknown region
sure_fg = np.uint8(sure_fg)
unknown = cv2.subtract(sure_bg,sure_fg)
        # Marker labelling
ret, markers = cv2.connectedComponents(sure_fg)
print(markers)
        # Add one to all labels so that sure background is not 0, but 1
markers = markers+1
        # Now, mark the region of unknown with zero
markers[unknown==255] = 0
markers = cv2.watershed(scr,markers)
scr[markers == -1] = [0,0,255]
print(markers)
scr[440:480,200:480]=0
cv2.imshow('scr1',scr)
cv2.imshow('mask',thresh)
q=cv2.waitKey(1)
# if q == 27:
time.sleep(60)
cv2.destroyAllWindows()